FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
        python3-pip \
        python3-dev \
        patchelf \
    && pip3 install --upgrade cython auditwheel \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
